[package]
name = "cosmosbootloader"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "cosmosbootloader"
path = "src/main.rs"

[dependencies]
# None, CosmosBootloader is built using NASM
