# Cargo configuration for BIOS/UEFI bootloader

[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-T./boot/custom-uefi-linker.ld",
    "-C", "relocation-model=pic",
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
